# Generated by Django 4.2.3 on 2023-07-27 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Fitness', '0002_rename_commnet_contact_comment_alter_contact_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='date',
        ),
    ]
