# Generated by Django 4.2.3 on 2023-07-29 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fitness', '0003_remove_contact_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Signup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=100)),
                ('pass1', models.IntegerField()),
            ],
        ),
    ]
