# Generated by Django 4.2.3 on 2023-07-30 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Fitness', '0004_signup'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signup',
            old_name='pass1',
            new_name='passeord2',
        ),
        migrations.RenameField(
            model_name='signup',
            old_name='uname',
            new_name='username',
        ),
    ]
