# Generated by Django 4.2.3 on 2023-07-30 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Fitness', '0005_rename_pass1_signup_passeord2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signup',
            old_name='passeord2',
            new_name='password1',
        ),
    ]
