# Generated by Django 4.2.3 on 2023-07-30 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Fitness', '0006_rename_passeord2_signup_password1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Signup',
        ),
    ]
